### ISSUE TITLE
Kicad fait une erreur au démarrage

### ISSUE THREAD

**Issue by f4bjh** [f8kgl/swr_power_meter#101]
![image](https://user-images.githubusercontent.com/52258351/80141594-10bd5700-85aa-11ea-8ddd-cbdc3fc0939f.png)

**Comment by f4bjh** [comment]
Visiblement, est apparu avec ce commit : https://github.com/f8kgl/swr_power_meter/commit/f18413c56c2a7412bc5f6d7ad0c81c7bb11e8d8b#diff-fa0e92bc9e44e93ac15648b0c116433a

On dirait que le résultat d'un diff a été livré dans ce fichier.
=> suppression manuelle

**Comment by f4bjh** [comment]
André, tu me confirmes que ce message d'erreur a bien disparu chez toi aussi ?

**Comment by f4bjh** [comment]
André, est-ce que tu as toujours cette erreur ? (il faut que tu viennes voir cette fiche sur Github, pour me le confirmer ou pas...j'ai besoin de savoir si je peux ferme cette fiche ou pas, pour poser un tag)

**Comment by F0EOS** [comment]
je n'ai plus ce message d'erreur mais un autre
