### ISSUE TITLE
Driver ADC

### ISSUE THREAD

**Issue by f4bjh** [f8kgl/swr_power_meter#120]

**Comment by f4bjh** [comment]
commencer par implémenter l'ADC sous gpsim

**Comment by f4bjh** [comment]
Mon analyse pour la mise en oeuvre du LTC2305 sous gpsim : 

Exemple : composant i2c2par

Côté I2C, les données doivent passer, à un moment donné, par gpsim-0.30.0/src/i2c-ee.cc qui fait appel à get_data ou put_data.
Ces fonctions sont codées dans modules/i2c2par.cc, qui va charcher les données sur un "IOPort"


Du coup, ce qui vaudrait le coup ce serait : 
1/créer une branche sur le projet pour les developpements i2c
2/dans cette branche : 
2.1/mettre en oeuvre un driver i2c2par dans le PIC, qui récupère les valeurs du IOPort (fixé à une valeur sur 8 bits, par 01010101 (ou autre peu importe) => vérifier que l'on arrive bien à récupérer la valeur attendue
2.2/créer un nouveau composant stricitement identique à i2c2par, et refaire cette manip
2.3/faire évoluer le composant pour changer IOPort en un port qui reçoit une tension et la converti directement en hexa. La récupérer dans le PIC.

Question : faut-il refaire un make et make install de gpsim après modif d'un composant ?
j'ai installé gpsim par apt-get. Faut-il le désinstaller du coup ?

**Comment by f4bjh** [comment]
Régression avec ce commit https://github.com/f8kgl/swr_power_meter/commit/15b4c0a44294a39fe523f65b056f44dc60ba33b1

![image](https://user-images.githubusercontent.com/52258351/80736411-62b62d80-8b12-11ea-92bf-39162afab0ec.png)

Retour du pb de PCLATH ? #122

**Comment by f4bjh** [comment]
-->1/créer une branche sur le projet pour les developpements i2c
implémenté et validé (branche i2c_test)

-->2/dans cette branche :
-->2.1/mettre en oeuvre un driver i2c2par dans le PIC, qui récupère les valeurs du IOPort (fixé à une valeur sur 8 bits, par 01010101 (ou autre peu importe) => vérifier que l'on arrive bien à récupérer la valeur attendue

en cours
pb n°1 : impossible de driver SDA et SCL de i2c2par #131 
pb n°2 : plantage du PIC. Bloqué en PCL=0x0CE0 #130 


-->2.2/créer un nouveau composant stricitement identique à i2c2par, et refaire cette manip
-->2.3/faire évoluer le composant pour changer IOPort en un port qui reçoit une tension et la converti directement en hexa. La récupérer dans le PIC.

Non commencés

**Comment by f4bjh** [comment]
-->2/dans cette branche :
-->2.1/mettre en oeuvre un driver i2c2par dans le PIC, qui récupère les valeurs du IOPort (fixé à une valeur sur 8 bits, par 01010101 (ou autre peu importe) => vérifier que l'on arrive bien à récupérer la valeur attendue

pb n°3 : la sortie de i2c2par vaut 0xD5 au lieu de 0xAA #132

**Comment by f4bjh** [comment]
pb n°4 : SCL=400kHz ??? #133

**Comment by f4bjh** [comment]
Pour créer une nouvelle librairie et un nouveau composant : 
1/créer un ficher source librairie.cc (sur le modèle de libgpsim_modules.cc)
2/créer un fichier source module.cc (sur le modèle de i2c2par.cc)
3/Adapter le Makefile.am (ajout de la librairie et du module)
4/
$cd .../gpsim.0.31
$ autoreconf
$./configure
$make
$sudo make install
$sudo /sbin/ldconfig

**Comment by f4bjh** [comment]
-->1/créer une branche sur le projet pour les developpements i2c
implémenté et validé (branche i2c_test)

-->2/dans cette branche :
-->2.1/mettre en oeuvre un driver i2c2par dans le PIC, qui récupère les valeurs du IOPort (fixé à une valeur sur 8 bits, par 01010101 (ou autre peu importe) => vérifier que l'on arrive bien à récupérer la valeur attendue

implémenté et validé (branche i2c_test)

-->2.2/créer un nouveau composant stricitement identique à i2c2par, et refaire cette manip
implémenté et validé (branche i2c_test)
avec malgré un petit souci non rédhibitoire a priori : #136 
-->2.3/faire évoluer le composant pour changer IOPort en un port qui reçoit une tension et la converti directement en hexa. La récupérer dans le PIC.

**Comment by f4bjh** [comment]
Pour rappel içi, pour placer un scope sous gpsim : 

**gpsim> scope.ch0="porta3"
**gpsim> scope.ch1="porta2"

**Comment by f4bjh** [comment]
reste à implémenter : 

1/CH1
2/les octets de commande du ltc2305

**Comment by F0EOS** [comment]
c est quoi tout ces composant que je vois defile

Ca sera a rajouter ?


Il va falloir faire du 2 face on ne pourrapas faire tout tenir sur une



----- Mail d'origine -----
De: Fabrice DECROP LONGET <notifications@github.com>
À: f8kgl/swr_power_meter <swr_power_meter@noreply.github.com>
Cc: Andre <F0EOS@FREE.FR>, Comment <comment@noreply.github.com>
Envoyé: Tue, 05 May 2020 21:12:33 +0200 (CEST)
Objet: Re: [f8kgl/swr_power_meter] Driver ADC (#120)

Pour rappel içi, pour placer un scope sous gpsim : 



**gpsim> scope.ch0="porta3"

**gpsim> scope.ch1="porta2"

**Comment by f4bjh** [comment]
> c est quoi tout ces composant que je vois defile Ca sera a rajouter ? Il va falloir faire du 2 face on ne pourrapas faire tout tenir sur une
> […](#)
> ----- Mail d'origine ----- De: Fabrice DECROP LONGET <notifications@github.com> À: f8kgl/swr_power_meter <swr_power_meter@noreply.github.com> Cc: Andre <F0EOS@FREE.FR>, Comment <comment@noreply.github.com> Envoyé: Tue, 05 May 2020 21:12:33 +0200 (CEST) Objet: Re: [f8kgl/swr_power_meter] Driver ADC (#120) Pour rappel içi, pour placer un scope sous gpsim : **gpsim> scope.ch0="porta3" **gpsim> scope.ch1="porta2"
> -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#120 (comment)](https://github.com/f8kgl/swr_power_meter/issues/120#issuecomment-624251174)

Tu n'es pas concerné par tout ça...c'est la simulation sous gpsim...

**Comment by f4bjh** [comment]
il manque encore la table de calibration de test

**Comment by f4bjh** [comment]
référence à 142 ci-dessus eronnée

**Comment by f4bjh** [comment]
https://github.com/f8kgl/swr_power_meter/commit/5d00e68406ee17e5fcb0c368d43a4d25a3c3e9fb


restrictions non bloquantes d'ores et déjà connues (liées à gpsim a priori) : 
-pas de tempo pour la conversion (normalement, 1,3us) #180
-1ère trame renvoie NACK #134 #159

A faire apparaître dans la doc d'implémentation V0.7

**Comment by f4bjh** [comment]
et à reporter sur la doc V0.8
