### ISSUE TITLE
changement de nom librairie 

### ISSUE THREAD

**Issue by F0EOS** [f8kgl/swr_power_meter#125]
il faudra essaye de changer le nom de la librairie "16F88" en "composants projet"

et faire les essai de fonctionnement pour savoir si KICAD fais bien appel a la nouvelles  

je te l'assigne quand meme pour un suivi au cas ou 
je vais essayer de faire ca dans les jours qui viennent

**Comment by f4bjh** [comment]
avec le commit précédent https://github.com/f8kgl/swr_power_meter/commit/a913d3da5b06c726f6fa0e540a10e91034a88256, j'ai fait un peu de nettoyage

Dorénavant, il y a une librairie qui s'apelle swr_power_meter.lib.

Que tu peux retrouver içi dans l'éditeur de schéma sous le nom "librairie_projet" : 
![image](https://user-images.githubusercontent.com/52258351/80788619-ee1ed580-8b89-11ea-8e0b-2bf1f9be7890.png)


Peux-tu vérifier que tout ça marche bien chez toi ?

Dans le doute, fais une recherche "AD5175" quand tu cherches à ajouter un composant au schéma
