### ISSUE TITLE
Tempo un peu longue sur le message d'acceuil ?

### ISSUE THREAD

**Issue by f4bjh** [f8kgl/swr_power_meter#127]
Je trouve la tempo du message d'acceuil un peu longue.

Est-elle conforme à la spec ?
=>la chronométrer et vérifier aussi qu'elle correspond bien à l'implémentation dans le code...

**Comment by f4bjh** [comment]
Tempo de 5 secondes conforme aux spécifications (Q=4MHz).

=>trop long ?

**Comment by f4bjh** [comment]
André, F0EOS : est-ce qu'elle est trop longue cette tempo d'après toi ?

voir p 15/26 des specs : https://github.com/f8kgl/swr_power_meter/blob/i2c_test/doc/SWR_POWER_METER_F8KGL_specifications_v0.7.pdf

**Comment by F0EOS** [comment]
3s serais pas mieux ?

**Comment by f4bjh** [comment]
Oui, je suis d'accord
