### ISSUE TITLE
Ajouter le LT1818 au schéma

### ISSUE THREAD

**Issue by f4bjh** [f8kgl/swr_power_meter#168]
Poser le composant LT1818 au schéma (sans autre ajout supplémentaire pour le moment)

Même principe que la #164

**Comment by F0EOS** [comment]
pas dispo dans la bibliothèque de KICAD

faut que je le face 

tu le veux en MSOP 8 ou T-SOT23 ?

**Comment by f4bjh** [comment]
exact...la doc n'est pas assez précise...

je complète cela dès que possible. #171 bloquant

**Comment by f4bjh** [comment]
#172 bloquant

**Comment by f4bjh** [comment]
référence ci-dessus erronée

**Comment by f4bjh** [comment]
Ahhh y est !!!

On en était là, tu te souviens ?

Tu trouveras tout ce qu'il te manque (a priori, et sauf oubli involontaire de ma part) içi : 

https://github.com/f8kgl/swr_power_meter/blob/master/doc/SWR_POWER_METER_F8KGL_specifications_V0.7.pdf

Pour le moment, dans cette fiche, il n'est question "QUE" de poser le composant LT1818 au schéma (sans autre ajout supplémentaire pour le moment)

**Comment by f4bjh** [comment]
#118

**Comment by f4bjh** [comment]
Very very good job !!! :-)
