### ISSUE TITLE
LIBRAIRIE PROJET

### ISSUE THREAD

**Issue by F0EOS** [f8kgl/swr_power_meter#191]
lors de la création du LT818 et sont enregistrement j'avais deux dossier librairie projet PK ??

dans les post  librairie projet n'a pas ete poste, il ne sais pas sélectionner automatiquement normal ??

**Comment by f4bjh** [comment]
Sous Kicad, dans l'éditeur de schéma, peux tu aller dans "Préférences->Configurer les librairies de symbole ->Librairies Spécifiques au Projet" ? 

Et faire une copie d'écran

**Comment by f4bjh** [comment]
#168

**Comment by f4bjh** [comment]
André : 

**1/Problème de librairie**
Sous Kicad, dans l'éditeur de schéma, peux tu aller dans "Préférences->Configurer les librairies de symbole ->Librairies Spécifiques au Projet" ?

Et faire une copie d'écran

**2/Erreur nom de composant**
attention, le nom du composant ajouté est erroné.
Il faut mettre LT1818 et non pas LT818

**3/Oubli de la chaine "REF**
Si tu regardes bien les specs, il faut deux fois le composant AD5175, et deux fois le composant LT1818

Voilà, voilà

**Comment by f4bjh** [comment]
Je suppose donc que ton problème de librairie est finalement résolu.
