### ISSUE TITLE
cablage verification et question

### ISSUE THREAD

**Issue by F0EOS** [f8kgl/swr_power_meter#292]
Verifier R3
Cablage U5 fait
Verifier borne 10 de U7

condensateur c27 et c28 non raccordé , c'etait  les capa de filtrage de U8 qui est maintenant alimenter via U7

c'est un peu contradictoire avec  les explications que tu m'a donne concernant les alimentation de chaque composants 
Du coup je ne comprends plus vraiment

**Comment by f4bjh** [comment]
R3 => OK
U5 => OK
Borne 10 de U7 => OK


Pour répondre à ta question : 
C16, C17 découple U7
C27, C28 découple U8
C21, C22 découple U6

D'accord ?
