### ISSUE TITLE
ajouter un pont diviseur de tension

### ISSUE THREAD

**Issue by f4bjh** [f8kgl/swr_power_meter#302]
ajouter au schéma un pont diviseur de tension, voir spec p23 et 28

**Comment by f4bjh** [comment]
#289

**Comment by f4bjh** [comment]
cette fiche est toujours ouverte

voir p19

**Comment by MonFrancoue** [comment]
j'ai refais une modif en lisant la compensation en temperature je pense que
le pont ressemble plus a ce qu il faut

**Comment by f4bjh** [comment]
voir p15 des specs pour le pont diviseur côté ADC

**Comment by f4bjh** [comment]
Je pense qu'il manque le pont divisuer côté ADC : 16 §3.8.2

**Comment by f4bjh** [comment]
#289
