### ISSUE TITLE
Rajouter un interrupteur en série avec le pack pile

### ISSUE THREAD

**Issue by f4bjh** [f8kgl/swr_power_meter#31]
pour couper l’alimentation par le pack pile. Sur alim externe, le branchement suffit à faire démarrer le système

**Comment by F0EOS** [comment]
Voir avec Jack Alim qui coupe les pile si alimentation via Alimentation Stabilise

**Comment by f4bjh** [comment]
https://github.com/f8kgl/swr_power_meter/commit/9dbf88e6ae1ed61137ce3cdc3c19a4f8113eb1b9
