### ISSUE TITLE
Petite erreur au schéma

### ISSUE THREAD

**Issue by f4bjh** [f8kgl/swr_power_meter#318]
Voici une fiche pour commencer avec github, Kicad, etc...
Il y a une petite bourde au schéma : il y a un fil en l'air sur le fil de donnée du bus I2C

![Screenshot_20210217_230410](https://user-images.githubusercontent.com/52258351/108274302-faa20800-7174-11eb-81e4-c1a574b94f93.png)
![Screenshot_20210217_230823](https://user-images.githubusercontent.com/52258351/108274396-22916b80-7175-11eb-987f-5221f90fd228.png)

Il faut connecter ces 2 petits fils en l'air :-)

bloquant pour #289

**Comment by MonFrancoue** [comment]
le fil est reconnecte 
j espere maintenant que le fichier est mis a jour

**Comment by f4bjh** [comment]
aïe...je te confirme ce que l'on se disait avec André : à ce jour, pas vu, ni reçu de mise à jour du schéma pour cette fiche :-p

**Comment by MonFrancoue** [comment]
Bonsoir Fabrice

Il semble que ce soit une histoire de droit insuffisant pour livrer les
modifications

**Comment by f4bjh** [comment]
C'est bon, ça passe. Je passe cette fiche en "terminé"
