### ISSUE TITLE
supprimer U8

### ISSUE THREAD

**Issue by f4bjh** [f8kgl/swr_power_meter#334]
suite à https://github.com/f8kgl/swr_power_meter/commit/e914692e678b05e6d7258ca977febf84a28a309a

supprimer U8 du schéma

**Comment by f4bjh** [comment]
#289

**Comment by MonFrancoue** [comment]
Bonjour Fabrice,

Avant de faire une betise je te demande pour etre sur ,Tu veux que l'on
supprime la mémoire  c'est bien cela ?

**Comment by f4bjh** [comment]
Absolument, oui !!!

**Comment by f4bjh** [comment]
ok. Vu.
