### ISSUE TITLE
Cablage MAX 4624

### ISSUE THREAD

**Issue by F0EOS** [f8kgl/swr_power_meter#38]
IN commande PIC
GNG Et COM  masse
V+  alimentation +5v
NO et NC  vers FWD et REF

**Comment by f4bjh** [comment]
Suite au commit 4f309e5536476682bc40797a770bac94114bafbe, rajouter au schéma les switch du §3.4.1 des spécifications (doc/SWR_POWER_METER_F8KGL_specifications.ods p 23)

**Comment by f4bjh** [comment]
avec le passage en V0.7, le switch devient inutile
