### ISSUE TITLE
Spécifier le boitier

### ISSUE THREAD

**Issue by f4bjh** [f8kgl/swr_power_meter#40]

**Comment by f4bjh** [comment]
§3.1.1
Dimensions = 155x80x100 (mm

Est-ce suffisant ?

**Comment by F0EOS** [comment]
155 de large OK
80 de hauteur  ok voir un peu plus petit reste a déterminer en fonction de l'afficheur
profondeur 100 pk pas 70 me parait pas mal non plus

Reste a affiner les dimensions en fonction de ce que l'on mettra dedans et son agencement

**Comment by f4bjh** [comment]
#223
