### ISSUE TITLE
probleme de post 

### ISSUE THREAD

**Issue by F0EOS** [f8kgl/swr_power_meter#74]
probleme de post  a chaque envoie j'ai ce msg 

![IMG-20190709-WA0000](https://user-images.githubusercontent.com/52300772/60910537-5ca04900-a281-11e9-88c8-e368a8d5147e.jpeg)

**Comment by f4bjh** [comment]
Visiblement, il faut **d'abord** se mettre à jour avant d'uploader une modif quelqueconque

Si je ne dis pas de bêtise, cliquer sur "Git Sync", pour faire la synchronisation

Pour rappel, uplader une modif, se dit aussi "faire un commit", ou faire "git push"
Se synchroniser (menu Git sync dans Windows") se dit aussi "faire un git pull"

**Comment by f4bjh** [comment]
Peux -tu vérifer ce que je dis là ? C'est à dire : 

1-faire une modif bidon dans le schéma
2-Faire Git Sync
3-Faire le commit, et vérifier que tu n'as plus de message d'erreurs. Dans le cas contraire, poster içi même la copie d'écran de l'erreur

**Comment by f4bjh** [comment]
C'est bon ? C'est résolut du coup ?

**Comment by f4bjh** [comment]
On peut fermer ce bug ?

**Comment by F0EOS** [comment]
Je suis passer sous W10 donc plus rien sur le pc

J au reinstaller kicad et rien d autre 

Fait que je re installe tout le reste sauf que je me souviens pas, me souviens pas de parametre et mot de passe mais surtout comment ca refonctionne

Donc besoin tuto par mail lol

Donc je ne peux pas te repondre

----- Mail d'origine -----
De: Fabrice DECROP LONGET <notifications@github.com>
À: f8kgl/swr_power_meter <swr_power_meter@noreply.github.com>
Cc: F0EOS <F0EOS@FREE.FR>, Assign <assign@noreply.github.com>
Envoyé: Sun, 05 Jan 2020 17:39:23 +0100 (CET)
Objet: Re: [f8kgl/swr_power_meter] probleme de post (#74)

On peut fermer ce bug ?

**Comment by f4bjh** [comment]
OK.

En attendant que tu remontes ton système, je ferme ce bug. 

Au besoin, on le rouvrira si tu as de nouveaux des problèmes similaires.
