### ISSUE TITLE
Caracteristique FR4

### ISSUE THREAD

**Issue by F0EOS** [f8kgl/swr_power_meter#75]
je ne comprends pas la correspondance des caracteristique du FR4 pour paramettre QUBS

De meme en parametre par default j'ai des piste large de 2 ou 3 mm et je trouve cela bizarre

[CARACTERISTIQUE FR4.xlsx](https://github.com/f8kgl/swr_power_meter/files/3374361/CARACTERISTIQUE.FR4.xlsx)

**Comment by f4bjh** [comment]
Tout d'abord, pour info : commit 94bb4ea00321671a34b73466ccb6c8338c337daf

**NE PAS UTILISER D'ESPACE DANS LES NOMS DE FICHIERS OU DE REPERTOIRE**
Préferer le caractère "underscore", ou tiret du chiffre 8

**Comment by f4bjh** [comment]
Dans QUCS, pourrais-tu me dire quels sont les paramètres qui te manquent exactement ?

**Comment by F0EOS** [comment]
tous je ne comprends pas les correspondances entre les caracteristique du FR4 et les parametre de Qucs

**Comment by f4bjh** [comment]
Dans QUCS, avec l'outil qui fait la synthèse de la ligne imprimée, si tu passes la souris juste au dessus du nom du paramètre, il te dit de quoi il s'agit.

Exemple : "Er" ----> Permitivité relative ==> Google est ton ami
[https://fr.wikipedia.org/wiki/Permittivit%C3%A9](url)

Et là, tu apprends que la permitivité relative est la même chose que la constante diélectrique.
"Mur" ---> Perméabilité relative ==> Google est ton ami 

[https://fr.wikipedia.org/wiki/Perm%C3%A9abilit%C3%A9_magn%C3%A9tique](url)


et ainsi de suite...
