### ISSUE TITLE
Comment fait-on pour répondre sur Github ?

### ISSUE THREAD

**Issue by f4bjh** [f8kgl/swr_power_meter#82]
Quand on poste un issue, GitHub envoie un mail aux personnes concernées, avec le contenu de l'issue. Par ex : 
>
>
> §3.1.1
> Dimensions = 155x80x100 (mm
>
> Est-ce suffisant ?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.

Pour y répondre, il faut : 
1-Cliquer sur "view it on GitHub"
2-Répondre dans l'espace commentaire, située en dessous 
![Comment répondre sur GitHub](https://user-images.githubusercontent.com/52258351/61034595-dccfc700-a3c5-11e9-8a9d-99c5b51c713f.jpg)

**Comment by f4bjh** [comment]
Est-ce que ça répond à ta question ?

**Comment by F0EOS** [comment]
pas connecter donc pas de fenêtre réponse
